<?xml version="1.0" ?>
<robot name="drone" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find drone_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find drone_description)/urdf/drone.gazebo.xacro"/>

  <xacro:property name="D435_cam_rgb_px" value="0.005"/>
  <xacro:property name="D435_cam_rgb_py" value="0.018"/>
  <xacro:property name="D435_cam_rgb_pz" value="0.013"/>
  <xacro:property name="D435_cam_depth_offset" value="0.01"/>

  <link name="base_footprint"/>
  <link name="base_link">
    <visual name ="base_link_visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/iris.dae"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <visual name ="front_left_leg_visual">
      <origin xyz="0.123 0.22 -0.11" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.17" radius="0.005"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <visual name ="front_right_leg_visual">
      <origin xyz="0.123 -0.22 -0.11" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.17" radius="0.005"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <visual name ="rear_left_leg_visual">
      <origin xyz="-0.140 0.21 -0.11" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.17" radius="0.005"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <visual name ="rear_right_leg_visual">
      <origin xyz="-0.140 -0.21 -0.11" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.17" radius="0.005"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0 -0.08" rpy="0 0 0"/>
      <geometry>
        <box size="0.47 0.47 0.23"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="0.008" ixy="0" ixz="0"
               iyy="0.015" iyz="0"
               izz="0.017" />
    </inertial>
  </link>
  <link name="odometry_sensorgt_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia ixx="0.0001" ixy="0" ixz="0"
               iyy="0.0002" iyz="0"
               izz="0.0002" />
    </inertial>
  </link>
  <link name="imu_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia ixx="0.00001" ixy="0" ixz="0"
               iyy="0.00002" iyz="0"
               izz="0.00002" />
    </inertial>
  </link>
  <link name="table_1_link">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 1.57"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/TableSquareLegs_Collada.dae" scale="0.05 0.05 0.05"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0.0" rpy="0 0 1.57"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/TableSquareLegs_Collada.dae" scale="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 1.57"/>
      <mass value="0.001" />
      <inertia ixx="0.0000001" ixy="0.0" ixz="0.0"
               iyy="0.0000002" iyz="0.0"
               izz="0.0000002" />
    </inertial>
  </link>
  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 -1.57"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/rplidar.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 -1.57"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/rplidar.dae" scale="0.001 0.001 0.001"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="1.57 0 -1.57"/>
      <mass value="0.001" />
      <inertia ixx="0.0000001" ixy="0.0" ixz="0.0"
               iyy="0.0000002" iyz="0.0"
               izz="0.0000002" />
    </inertial>
  </link>
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/d435.dae"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/d435.dae"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001" />
      <inertia ixx="0.0000001" ixy="0.0" ixz="0.0"
               iyy="0.0000002" iyz="0.0"
               izz="0.0000002" />
    </inertial>
  </link>
  <link name="camera_rgb_frame"/>
  <link name="camera_rgb_optical_frame"/>
  <link name="camera_depth_frame"/>
  <link name="camera_depth_optical_frame"/>
  <link name="rotor_0">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/iris_prop_ccw.dae"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.005" radius="0.1"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia ixx="0.000009750" ixy="0" ixz="0"
               iyy="0.000166704" iyz="0"
               izz="0.000167604" />
      </inertial>
    </link>
  <link name="rotor_1">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/iris_prop_ccw.dae"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.005" radius="0.1"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia ixx="0.000009750" ixy="0" ixz="0"
               iyy="0.000166704" iyz="0"
               izz="0.000167604" />
      </inertial>
    </link>
  <link name="rotor_2">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/iris_prop_cw.dae"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.005" radius="0.1"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia ixx="0.000009750" ixy="0" ixz="0"
               iyy="0.000166704" iyz="0"
               izz="0.000167604" />
      </inertial>
  </link>
  <link name="rotor_3">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://drone_description/meshes/iris_prop_cw.dae"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.005" radius="0.1"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.025"/>
      <inertia ixx="0.000009750" ixy="0" ixz="0"
               iyy="0.000166704" iyz="0"
               izz="0.000167604" />
    </inertial>
  </link>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0.194923" rpy="0 0 0"/>
  </joint>
  <joint name="odometry_sensorgt_joint" type="revolute">
    <parent link="base_link"/>
    <child link="odometry_sensorgt_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="0" upper="0" />
    <dynamics damping="1" friction="0"/>
  </joint>
  <joint name="imu_joint" type="revolute">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="0" upper="0" />
    <dynamics damping="1" friction="0"/>
  </joint>
  <joint name="table_1_joint" type="revolute">
    <parent link="base_link"/>
    <child link="table_1_link"/>
    <origin xyz="0.05 0 0.035" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="0" upper="0" />
    <dynamics damping="1" friction="0"/>
  </joint>
  <joint name="scan_joint" type="fixed">
    <parent link="table_1_link"/>
    <child link="base_scan"/>
    <origin xyz="0 0 0.053" rpy="0 0 3.141593"/>
  </joint>
  <joint name="camera_joint" type="revolute">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.07 0 0.057" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="0" upper="0" />
    <dynamics damping="1" friction="0"/>
  </joint>
  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${D435_cam_rgb_px} ${D435_cam_rgb_py} ${D435_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${D435_cam_rgb_px} ${D435_cam_rgb_py + D435_cam_depth_offset} ${D435_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <joint name="rotor_0_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rotor_0"/>
    <origin xyz="0.13 -0.22 0.023" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="-1" velocity="-1"/>
    <dynamics damping="0.004" friction="0"/>
  </joint>
  <joint name="rotor_1_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rotor_1"/>
    <origin xyz="-0.13 0.2 0.023" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="-1" velocity="-1"/>
    <dynamics damping="0.004" friction="0"/>
  </joint>
  <joint name="rotor_2_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rotor_2"/>
    <origin xyz="0.13 0.22 0.023" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="-1" velocity="-1"/>
    <dynamics damping="0.004" friction="0"/>
  </joint>
  <joint name="rotor_3_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rotor_3"/>
    <origin xyz="-0.13 -0.2 0.023" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="-1" velocity="-1"/>
    <dynamics damping="0.004" friction="0"/>
  </joint>
</robot>
