<?xml version="1.0" ?>
<robot name="dam-typhoon" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find dam-drone)/xacro/color_properties.xacro"/>
  <xacro:include filename="$(find dam-drone)/xacro/gazebo.xacro"/>

  <xacro:property name="D435_cam_rgb_px" value="0.005"/>
  <xacro:property name="D435_cam_rgb_py" value="0.018"/>
  <xacro:property name="D435_cam_rgb_pz" value="0.013"/>
  <xacro:property name="D435_cam_depth_offset" value="0.01"/>

  <xacro:arg name="robot_namespace" default="/" />

  <!-- Typhoon H body -->
  <origin rpy="0 0 0" xyz="1.0 1.0 3.0"/>
  <link name="base_link">
    <origin rpy="0 0 0" xyz="0 -0 0"/>
    <inertial>
      <mass value="2.02"/>
      <inertia ixx="0.011" ixy="0" ixz="0" iyy="0.015" iyz="0" izz="0.021"/>
    </inertial>
    <collision>
      <geometry>
        <box size="1.34 1.34 1"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/main_body_remeshed_v3.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="darkgrey"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>

  <link name="cgo3_mount_link">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <!-- place holder -->
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/cgo3_mount_remeshed_v1.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="cgo3_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="cgo3_mount_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- <limit effort="100" lower="0" upper="0" velocity="-1"/> -->
    <dynamics damping="1"/>
  </joint>

    <link name="cgo3_vertical_arm_link">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <!-- place holder -->
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/cgo3_vertical_arm_remeshed_v1.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="cgo3_vertical_arm_joint" type="fixed">
    <parent link="cgo3_mount_link"/>
    <child link="cgo3_vertical_arm_link"/>
    <origin rpy="0 0 0" xyz="0 0 0.0"/>
    <!--
    <controlIndex>6</controlIndex>
    -->
    <axis xyz="0 0 1"/>
    <!-- <limit effort="100" lower="-1e16" upper="1e16" velocity="-1"/> -->
    <dynamics damping="0.1"/>
  </joint>

  <link name="cgo3_horizontal_arm_link">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <!-- place holder -->
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/cgo3_horizontal_arm_remeshed_v1.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>
  <joint name="cgo3_horizontal_arm_joint" type="fixed">
    <parent link="cgo3_vertical_arm_link"/>
    <child link="cgo3_horizontal_arm_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <!--
    <controlIndex>7</controlIndex>
    -->
    <axis xyz="-1 0 0"/>
    <!-- <limit effort="100" lower="-0.785398" upper="0.785398" velocity="-1"/> -->
    <dynamics damping="0.1"/>
  </joint>

  <link name="cgo3_camera_link">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <!-- place holder -->
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/cgo3_camera_remeshed_v1.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin rpy="0 -0 0" xyz="-0.1642 0 -0.324"/>
      <geometry>
        <sphere radius="0.035"/>
      </geometry>
    </collision>
    <sensor name="camera_imu" type="imu">
      <always_on>true</always_on>
    </sensor>
    <sensor name="camera" type="camera">
      <camera>
        <image far="15000" format="R8G8B8" height="360" hfov="2.0" near="0.05" width="640"/>
      </camera>
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <visualize>false</visualize>
    </sensor>
  </link>
  <joint name="cgo3_camera_joint" type="fixed">
    <parent link="cgo3_horizontal_arm_link"/>
    <child link="cgo3_camera_link"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <!-- <limit effort="100" lower="-0.0872665" upper="1.5708" velocity="-1"/> -->
    <dynamics damping="0.1"/>
  </joint>
-->

  <link name="left_leg">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <!-- place holder -->
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <collision>
      <origin rpy="7.9 4.95 4.68" xyz="-0.01 -0.28628 -0.414504"/>
      <geometry>
        <cylinder length="0.6" radius="0.030418"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="-0.552636 0 0" xyz="0.00104 -0.17006 -0.242374"/>
      <geometry>
        <cylinder length="0.383786" radius="0.01829968"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/leg2_remeshed_v3.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="darkgrey"/>
    </visual>
  </link>
  <joint name="left_leg_joint" type="fixed">
    <parent link="base_link"/>
    <child link="left_leg"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="-1 0 0"/>
    <dynamics damping="0.1"/>
  </joint>

  <link name="right_leg">
    <origin rpy="0 0 0" xyz="0 -0 0"/>
    <inertial>
      <!-- place holder -->
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <collision>
      <origin rpy="7.9 4.95 4.68" xyz="-0.01 0.28628 -0.414504"/>
      <geometry>
        <cylinder length="0.6" radius="0.030418"/>
      </geometry>
    </collision>
    <collision>
      <origin rpy="0.552636 0 0" xyz="0.00104 0.17006 -0.242374"/>
      <geometry>
        <cylinder length="0.383786" radius="0.01829968"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/leg1_remeshed_v3.stl" scale="0.002 0.002 0.002"/>
      </geometry>
      <material name="darkgrey"/>
    </visual>
  </link>
  <joint name="right_leg_joint" type="fixed">
    <parent link="base_link"/>
    <child link="right_leg"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1"/>
  </joint>

  <link name="typhoon_h480/imu_link">
    <origin rpy="0 0 0" xyz="0 0 3.1415927"/>
    <inertial>
      <mass value="0.015"/>
      <inertia ixx="1e-05" ixy="0" ixz="0" iyy="1e-05" iyz="0" izz="1e-05"/>
    </inertial>
  </link>
  <joint name="typhoon_h480/imu_joint" type="revolute">
    <parent link="base_link"/>
    <child link="typhoon_h480/imu_link"/>
    <axis xyz="1 0 0"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>

<link name="rotor_3">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="9.75e-07" ixy="0" ixz="0" iyy="0.000273104" iyz="0" izz="0.000274004"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder length="0.128" radius="0.005"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/prop_ccw_assembly_remeshed_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>
  <joint name="rotor_3_joint" type="revolute">
    <origin xyz="0.211396 0.119762 0.0822169" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rotor_3"/>
    <axis xyz="0.0446 -0.0825 1.8977"/>
    <limit effort="10" lower="-1e+16" upper="1e+16" velocity="-1"/>
    <dynamics damping="0.005"/>
  </joint>

  <link name="rotor_0">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="9.75e-07" ixy="0" ixz="0" iyy="0.000273104" iyz="0" izz="0.000274004"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder length="0.128" radius="0.005"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/prop_ccw_assembly_remeshed_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>
  <joint name="rotor_0_joint" type="revolute">
    <origin xyz="-0.209396 0.122762 0.075" rpy="0 0 2.09439510239"/>
    <parent link="base_link"/>
    <child link="rotor_0"/>
    <axis xyz="0.046 0.0827 1.8977"/>
    <limit effort="10" lower="-1e+16" upper="1e+16" velocity="-1"/>
    <dynamics damping="0.005"/>
  </joint>

  <link name="rotor_4">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="9.75e-07" ixy="0" ixz="0" iyy="0.000273104" iyz="0" izz="0.000274004"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder length="0.128" radius="0.005"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/prop_cw_assembly_remeshed_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>
  <joint name="rotor_4_joint" type="revolute">
    <origin xyz="-0.00097896 0.242705 0.075" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="rotor_4"/>
    <axis xyz="-0.09563 -0.0003 1.8976"/>
    <limit effort="10" lower="-1e+16" upper="1e+16" velocity="-1"/>
    <dynamics damping="0.005"/>
  </joint>

  <link name="rotor_1">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="9.75e-07" ixy="0" ixz="0" iyy="0.000273104" iyz="0" izz="0.000274004"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder length="0.128" radius="0.005"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/prop_cw_assembly_remeshed_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>
  <joint name="rotor_1_joint" type="revolute">
    <origin xyz="0.211396 -0.119762 0.075" rpy="0 0 -2.09439510239"/>

    <parent link="base_link"/>
    <child link="rotor_1"/>
    <axis xyz="0.0486 0.0811 1.8976"/>
    <limit effort="10" lower="-1e+16" upper="1e+16" velocity="-1"/>
    <dynamics damping="0.005"/>
  </joint>

  <link name="rotor_5">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="9.75e-07" ixy="0" ixz="0" iyy="0.000273104" iyz="0" izz="0.000274004"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder length="0.128" radius="0.005"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/prop_ccw_assembly_remeshed_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>
  <joint name="rotor_5_joint" type="revolute">
    <origin xyz="-0.00097896 -0.242705 0.075" rpy="0 0 -2.09439510239"/>
    <parent link="base_link"/>
    <child link="rotor_5"/>
    <axis xyz="-0.033996 -0.0006 0.68216"/>
    <limit effort="10" lower="-1e+16" upper="1e+16" velocity="-1"/>
    <dynamics damping="0.005"/>
  </joint>

  <link name="rotor_2">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="9.75e-07" ixy="0" ixz="0" iyy="0.000273104" iyz="0" izz="0.000274004"/>
    </inertial>
    <collision>
      <geometry>
        <cylinder length="0.128" radius="0.005"/>
      </geometry>
    </collision>
    <visual>
      <geometry>
        <mesh filename="package://dam-drone/urdf/TyphoonH480/meshes/prop_cw_assembly_remeshed_v3.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <gravity>true</gravity>
    <self_collide>false</self_collide>
  </link>
  <joint name="rotor_2_joint" type="revolute">
    <origin xyz="-0.209396 -0.122762 0.082219" rpy="0 0 2.09439510239"/>
    <parent link="base_link"/>
    <child link="rotor_2"/>
    <axis xyz="0.0404 -0.0876 1.8976"/>
    <limit effort="10" lower="-1e+16" upper="1e+16" velocity="-1"/>
    <dynamics damping="0.005"/>
  </joint>

<!-- collision 다리에 안먹어서 땅바닥에 깐거
  <link name="under_collision_link">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <collision>
      <geometry>
        <box size="1 1 0.0001"/>
      </geometry>
    </collision>
  </link>

  <joint name="under_collision_joint" type="revolute">
    <parent link="base_link"/>
    <child link="under_collision_link"/>
    <axis xyz="1 0 0"/>
    <origin rpy="0 0 0" xyz="0 0 -1"/>
    <limit effort="0" lower="0" upper="0" velocity="0"/>
  </joint>
   -->
  
  <!--IMU
  <link name="imu_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.15"/>
      <inertia ixx="0.00001" ixy="0" ixz="0"
               iyy="0.00002" iyz="0"
               izz="0.00002" />
    </inertial>
  </link>
  <joint name="imu_joint" type="revolute">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0.5 0.5" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="0" upper="0" />
    <dynamics damping="1" friction="0"/>
  </joint>-->

  <!--CAMERA-->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
        <mesh filename="package://dam-drone/xacro/d435.dae"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
        <mesh filename="package://dam-drone/xacro/d435.dae"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.001" />
      <inertia ixx="0.0000001" ixy="0.0" ixz="0.0"
               iyy="0.0000002" iyz="0.0"
               izz="0.0000002" />
    </inertial>
  </link>
  <link name="camera_rgb_frame"/>
  <link name="camera_rgb_optical_frame"/>
  <link name="camera_depth_frame"/>
  <link name="camera_depth_optical_frame"/>

  <joint name="camera_joint" type="revolute">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.07 0 0.12" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="0" velocity="0" lower="0" upper="0" />
    <dynamics damping="1" friction="0"/>
  </joint>
  
  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${D435_cam_rgb_px} ${D435_cam_rgb_py} ${D435_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${D435_cam_rgb_px} ${D435_cam_rgb_py + D435_cam_depth_offset} ${D435_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint> 

  <!--Velodyne 16-->

  <link name="lidar_on_drone_link">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0.03" />
      <geometry>
        <cylinder radius="0.0316" length="0.0817"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <joint name="lidar_on_drone_joint" type="revolute">
    <origin xyz="0 0 0.065" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="lidar_on_drone_link"/>
    <limit upper="0" lower="0" effort="0" velocity="0"/>
  </joint>

  <joint name="lidar_base_mount_joint" type="revolute">
    <origin xyz="0 0 0.13" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="lidar_base_link"/>
    <limit upper="0" lower="0" effort="0" velocity="0"/>
  </joint>

  <link name="lidar_base_link">
    <inertial>
      <mass value="0.83"/>
      <origin xyz="0 0 0.03815"/>
      <inertia ixx="${(0.83 * (3.0*0.0516*0.0516 + 0.0717*0.0717)) / 12.0}" ixy="0" ixz="0"
        iyy="${(0.83 * (3.0*0.0516*0.0516 + 0.0717*0.0717)) / 12.0}" iyz="0"
        izz="${0.5 * 0.83 * (0.0516*0.0516)}"/>
    </inertial>
    <visual>
      <geometry>
        <mesh filename="package://velodyne_description/meshes/VLP16_base_1.dae" />
      </geometry>
    </visual>
    <visual>
      <geometry>
        <mesh filename="package://velodyne_description/meshes/VLP16_base_2.dae" />
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0.03815"/>
      <geometry>
        <cylinder radius="0.0516" length="0.0717"/>
      </geometry>
    </collision>
  </link>

  <joint name="lidar_base_scan_joint" type="revolute" >
    <origin xyz="0 0 0.038" rpy="0 0 0" />
    <parent link="lidar_base_link" />
    <child link="lidar"/>
    <limit upper="0" lower="0" effort="0" velocity="0"/>
  </joint>

  <link name="lidar">
    <inertial>
      <mass value="0.01"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="1e-7" ixy="0" ixz="0" iyy="1e-7" iyz="0" izz="1e-7"/>
    </inertial>
    <visual>
      <origin xyz="0 0 -0.0377" />
      <geometry>
        <mesh filename="package://velodyne_description/meshes/VLP16_scan.dae" />
      </geometry>
    </visual>
  </link>

</robot>
